version: "3.8"
services:
  app:
    build:
      context: ./docker/php
      args:
        - TZ=${TZ}
    ports:
      - ${APP_PORT}:8000
    volumes:
      - ${PROJECT_PATH}:/work
      - ./docker/ash:/etc/profile.d
      - ./logs:/var/log/php
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./docker/php/root:/etc/crontabs/root
      - ./docker/php/supervisord.conf:/etc/supervisord.conf
    working_dir: /work
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_DATABASE=${DB_NAME}
      - DB_USERNAME=${DB_USER}
      - DB_PASSWORD=${DB_PASS}
      # - MAIL_HOST=${MAIL_HOST}
      # - MAIL_PORT=${MAIL_PORT}
      - TZ=${TZ}
      - CACHE_DRIVER=redis
      - SESSION_DRIVER=redis
      - QUEUE_DRIVER=redis
      - REDIS_HOST=redis
    command: ash -c "supervisord -c /etc/supervisord.conf && crond && php-fpm"

  web:
    image: nginx:1.25-alpine
    depends_on:
      - app
    ports:
      - ${WEB_PORT}:80
    volumes:
      - ${PROJECT_PATH}:/work
      - ./logs:/var/log/nginx
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    environment:
      - TZ=${TZ}

  db:
    build:
      context: ./docker/mysql/
    volumes:
      - db-store:/var/lib/mysql
      - ./logs:/var/log/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - TZ=${TZ}
    ports:
      - ${DB_PORT}:3306

  node:
    image: node:20-alpine
    tty: true
    volumes:
      - ${PROJECT_PATH}:/work
    working_dir: /work

  redis:
    image: redis:7.0-alpine3.18
    volumes:
      - redis-store:/data
    ports:
      - "${REDIS_PORT}:6379"

  mail:
    image: axllent/mailpit:latest
    ports:
      - "8025:8025"
    environment:
      MP_DATA_FILE: /tmp/mailpit.db
      # MH_STORAGE: maildir
      # MH_MAILDIR_PATH: /tmp
    volumes:
      - maildir:/tmp


volumes:
  db-store:
  redis-store:
  maildir: {}
